Add extra secret for chat deployment
RocketChat/helm-charts pull request #131
Opened 2024-03-11 10:57 UTC by paunis

Add extra secret for chat deployment.
Usefull to store sensitive data for creating initial user like ADMIN_* env vars or custom OAUTH settings like Accounts_OAuth_Custom_* env vars.

2024-03-11 15:46 UTC, debdutdeb requested changes
Like this a lot !

2024-03-11 15:46 UTC, debdutdeb commented on rocketchat/values.yaml
> +  name: ""
This could be one string I believe 😬

2024-03-11 15:46 UTC, debdutdeb commented
Also if could add to the README file :)

2024-03-12 06:40 UTC, paunis commented on rocketchat/values.yaml
> +  name: ""
Updated as one string

2024-03-12 06:45 UTC, debdutdeb approved these changes

2024-03-12 06:45 UTC, merged